x-mongodb-base: &mongodb-base
  image: mongo:latest
  env_file: ./.env
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    MONGO_INITDB_DATABASE: ${DB_NAME}

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: 20
    env_file: ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=mongodb
    volumes:
      - "./src:/app/src"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    <<: *mongodb-base
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"

  mongodb-test:
    <<: *mongodb-base
    # Using tmpfs runs this in memory to make the tests faster
    tmpfs:
      - /data/db

volumes:
  mongo-data:
