x-app-base: &app-base
  build:
    context: .
    args:
      NODE_VERSION: 20
  env_file: ./.env
  volumes:
    - "./src:/app/src"

x-mongodb-base: &mongodb-base
  image: mongo:latest
  env_file: ./.env
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    MONGO_INITDB_DATABASE: ${DB_NAME}

services:
  app:
    <<: *app-base
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    <<: *mongodb-base
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
      # When this volume is present the image will initialize the database with
      # the script inside init-mongo/ when container is started for the first
      # time
      - ./init-mongo:/docker-entrypoint-initdb.d

  app-test:
    <<: *app-base
    profiles: ["manual"]
    environment:
      - DB_HOST=mongodb-test
    depends_on:
      - mongodb-test

  mongodb-test:
    profiles: ["manual"]
    <<: *mongodb-base
    ports:
      - "27018:27017"
    # Using tmpfs only persists data in memory so we can hopefully make the
    # tests faster and the test data ephemeral
    tmpfs:
      - /data/db

volumes:
  mongo-data:
